# Site settings.
title:       Identifiers.org
group:       Identifiers.org
email:       identifiers-org@ebi.ac.uk
domain:      https://docs.identifiers.org
baseurl:     ""
permalink: /:categories/:title:output_ext

# Root repo for this project.
repo:        "https://github.com/identifiers-org/identifiers-org.github.io"
source:      .
destination: ./_site
exclude:     [node_modules, .sass-cache, gulpfile.js, package.json, HOWTO.md, docker-compose.yml, .gitlab-ci.yml]
future:      false
lsi:         false
markdown:    kramdown
highlighter: rouge

plugins:
  - jekyll-toc
  - jekyll-relative-links
  - jekyll-sitemap
livereload: true
resolverUrl: "https://cloud.identifiers.org"
registryUrl: "https://registry.identifiers.org"